// <auto-generated />
namespace MVCTemplate.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CorectUserIdtypefrominttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorectUserIdtypefrominttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201605032005220_Corect UserId type from int to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
